# Pull open jde base image based on Alpine Linux.
FROM  openjdk:8-jre-alpine

# Define ENV variables.
ENV SCALA_VERSION 2.12.6
ENV SBT_VERSION 1.2.3

# Install Scala.
RUN \
  echo "$SCALA_VERSION $SBT_VERSION" && \
  mkdir -p /usr/lib/jvm/java-1.8-openjdk/jre && \
  touch /usr/lib/jvm/java-1.8-openjdk/jre/release && \
  apk add --no-cache bash && \
  apk add --no-cache curl && \
  curl -fsL http://downloads.typesafe.com/scala/$SCALA_VERSION/scala-$SCALA_VERSION.tgz | tar xfz - -C /usr/local && \
  ln -s /usr/local/scala-$SCALA_VERSION/bin/* /usr/local/bin/ && \
  scala -version && \
  scalac -version

# Install SBT.
RUN \
  curl -fsL https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xfz - -C /usr/local && \
  ln -s /usr/local/sbt/bin/* /usr/local/bin/ && \
  sbt sbtVersion

# Define working directory.
WORKDIR /hello

# Copy the current directory contents into the container.
COPY . /hello

# Run this when the container launches.
CMD sbt run